Notebook shows PCA usage
LinkedEarth/PyleoTutorials pull request #38
Opened 2023-05-30 19:17 UTC by CommonClimate

(will fail CI as the changes are not yet in the master branch)

2023-05-30 22:23 UTC, khider requested changes
Looks the comments I left on the app and make sure the notebooks would pass the tests (they do not)

2023-06-11 00:42 UTC, CommonClimate commented
This review was less than helpful, as it made a bunch of scattershot comments on nearly every notebook but the one this branch created. Please keep the comments focused otherwise we can't make progress.

2023-06-13 15:18 UTC, khider commented
Well, then tell me which notebook. Because I went by the differences shown in the NBReview and all of them had changes.

2023-06-13 15:56 UTC, CommonClimate commented
Sorry, the PR is called "Notebook shows PCA usage", so I thought it implicit that it was the PCA notebook I wanted feedback on.

2023-06-13 15:56 UTC, merged